---
- name: Install common packages
  become: true
  ansible.builtin.apt:
    name:
      - neovim
      - vim
      - ncdu
      - tmux
      - ranger
      - w3m
      - curl
      - htop
      - xclip
      - xsel
    state: present
  tags:
    - packages

- name: Ensure destination for custom binaries exists
  become: true # If copying to /usr/bin
  ansible.builtin.file:
    path: "/usr/local/bin" # Safer than /usr/bin
    state: directory
    mode: '0755'
  tags:
    - binaries

- name: Copy custom binaries
  become: true # If copying to /usr/bin
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.mconfig/{{ item }}"
    dest: "/usr/local/bin/{{ item }}" # Safer than /usr/bin
    mode: '0755'
    remote_src: true # Indicates that 'src' is on the remote machine
  loop:
    - git/redate
    - python/loadpy
  tags:
    - binaries
