set nocompatible              " be iMproved, required
filetype off                  " required

" General                                                                       
set number                                                                      
set encoding=utf-8                                                              
set showcmd                                                                     
set splitright                                                                  
set nowrap                                                                      
set tabstop=4 shiftwidth=4                                                      
set expandtab                                                                   
set lazyredraw                                                                  
set colorcolumn=80                                                              
highlight colorcolumn ctermbg=DarkBlue                                          
                                                                                
" Searching                                                                     
set hlsearch                                                                    
set incsearch                                                                   
set ignorecase                                                                  
set smartcase       

" Navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Resizing Splits
nnoremap <S-Right> <C-W><lt>
nnoremap <S-Left>  <C-W>>
nnoremap <S-Up>    <C-W>+
nnoremap <S-Down>  <C-W>-

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'davidhalter/jedi-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'Valloric/YouCompleteMe'
call vundle#end()            " required

filetype plugin indent on    " required

" NerdTree config
autocmd vimenter * NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-n> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let NERDTreeIgnore = ['\.pyc$']

" Airline
let g:airline#extensions#tabline#enabled = 1

" YCM & Jedi - Padawan I always shall be
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR> 

" ColorScheme
syntax enable
colorscheme monokai
