#!/usr/bin/python

__author__ = "Meet P. Shah"
__license__ = "Do Whatever The Fuck You Want"

import sys
import visdom

import scipy.misc as misc
import numpy as np

n_images = len(sys.argv) -1

vis = visdom.Visdom(env='main')

if vis.check_connection():
    for i in sys.argv[1:]:
        vis.image(misc.imread(i).transpose(2,0,1),
                  opts=dict(caption=i))
else:
    print "Please start server `python -m visdom.server`"

