#!/usr/bin/python

__author__ = "Meet P. Shah"
__license__ = "Do Whatever The Fuck You Want"

import os
import sys
import json
import pickle

import scipy.misc as misc
import numpy as np

n_files = len(sys.argv) -1


def print_info(filepath=None):
    ext = filepath.split('.')[-1]
    try:
        if ext == 'json':
            print("="*80)
            print(filepath)
            dic = json.load(open(filepath))
            print("Keys:" dic.keys())

        elif ext in ['png', 'jpg', 'bmp', 'JPG', 'tif']:
            print("="*80)
            print(filepath)
            print(misc.imread(filepath).shape)

        elif ext == 'pkl':
            print("="*80)
            print(filepath)
            print(pickle.load(open(filepath,'rb')))
        
        elif ext == 'npy':
            print("="*80)
            print(filepath)
            print(np.load(filepath).shape)

        else:
            print('Unkown file extension {} for file {}'.format(ext, filepath))

    except e:
        print('Exception while peeking file {} : {}'.format(filepath, e))

for path in sys.argv[1:]:
    if os.path.isfile(path):
        print_info(path)
    else:
        print('No File found at {}'.format(path))


