export ZSH=/home/meetshah1995/.oh-my-zsh
export TERM="xterm-256color"
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Git aliases
alias ga="git add"
alias gc="git commit -m"
alias gp="git push"

# Utility
alias naut="nautilus ."
alias mp3='youtube-dl --extract-audio --audio-format mp3'
alias jn='jupyter notebook'
alias tatti="printf '\e[?2004l'"
alias cgrep="grep -B 5 -A 5"

# VPN Aliases
alias instiin="sudo systemctl start openvpn@iitbvpn.service"
alias instiout="sudo systemctl stop openvpn@iitbvpn.service"

# SSH Aliases (Copy from private file)


function gdate_() { sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z" } 
alias gdate="gdate_"


export CUDA_HOME=/usr/local/cuda-8.0
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

echo "$(tput setaf 7)Todo List $(tput sgr0)"

cat /home/meetshah1995/misc_code/meetshah1995.github.io/TODO.md

